[package]
name = "locenv"
version = "0.4.0"
description = "A library to aid on module development for locenv"
repository = "https://github.com/locenv/mdl-rust"
license = "MIT"
edition = "2021"

[dependencies]
