name: CD
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-20.04
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Publish locenv
      run: cargo publish -p locenv
    - name: Publish locenv-macros
      run: cargo publish -p locenv-macros
